[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/googlee092b1d073fd249e.html"
  to = "/googlee092b1d073fd249e.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200